### ISSUE TITLE
Allow option default value 0

### ISSUE THREAD

**Issue by MrHash** [lightningd/clightningjs#10]
When adding a plugin option of integer type with a default value of 0, the plugin evaluates this as false and the plugin is killed. The following line is where the error arises: https://github.com/lightningd/clightningjs/blob/master/src/plugin.js#L131. This seems to arise since the clightning v0.9.3 release.

Probably it's better to check explicitly for null values?

**Comment by darosior** [comment]
Yeah, definitely. Will take a look ASAP but happy to review a PR too (@anyonereadingthis)

**Comment by MrHash** [comment]
ok i'll post a PR later

**Comment by darosior** [comment]
Fixed by #11
